name: Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t boltgun69/docker-react-demo -f Dockerfile.dev .
      - run: docker run -e CI=true boltgun69/docker-react-demo npm test
